export const IS_DRIVER = 'IS_DRIVER'
export const START_TIME = 'START_TIME'
export const END_TIME = 'END_TIME'
export const ORIGIN_LOCATION = 'ORIGIN_LOCATION'
export const DEST_LOCATION = 'DEST_LOCATION'
